### ISSUE TITLE
Avoid ALL_CAPS for global variables

### ISSUE THREAD

**Issue by timrae** [SRombauts/SQLiteCpp#146]
Most C++ style guides (for example CppCoreGuidelines [NL.9](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-all-caps) and Google) say never to use all-caps unless you're defining a macro. This is because macros are unscoped and break your namespace encapsulation.

E.g see the following recipe for disaster:

```c++
// foo.h
#define OPEN_URI = 1
```

```c++
// main.cpp
#include "foo.h"
#include "SQLiteCpp/Database.h"

int main(int argc, char **argv) {
  // ...
  return 0;
}
```

**Comment by SRombauts** [comment]
Hi @timrae, I am all with you for this, but what is your point? I mean, can you tell me what you would like to fix.

**Comment by timrae** [comment]
@SRombauts 
I don't currently have any library that's breaking SQLiteCpp for me, but am simply suggesting changing the naming convention so as to prevent this from happening in the future. This happened to me today with another library and I had to go through and change all of the the constants to use `CamelCase` instead of `ALL_CAPS` inline with modern C++ guidelines.

**Comment by timrae** [comment]
(I realize this would probably be a controversial breaking change, I'm just putting it out there)

**Comment by SRombauts** [comment]
I am closing this, because I think that I have done it right: the only constant variables ALL_CAPS are inside the SQLite C++ namespace, so that the C #define SQLITE_OPEN_URI translate well to SQLite::OPEN_URI

ALL_CAPS here means that it is mapping to an official sqlite3 define.

Also, I understand that using a macro OPEN_URI could break this, but I am not willing to change this for now. If you think it is important, please do it and PR so I'll check how it look likes
