### ISSUE TITLE
Better MSVC support

### ISSUE THREAD

**Issue by jowr** [SRombauts/SQLiteCpp#168]
Thanks again for the nice work. I am willing to help improving the MSVC support and I would appreciate, if anyone could help me get started. Here is my question:

- Where should I start to add support for other compilers than MSVC 2015? 

The docs correctly mention that only MSVC 2015 is supported, but there are a a few examples and build scripts around that refer to other versions of Visual Studio. 

Additionally, I also think we should consider fixing the problems with MSCV2017.

You can see the build logs and my latest changes at: https://ci.appveyor.com/project/jowr/sqlitecpp/builds/20611322

**Comment by jowr** [comment]
OK, MSVC 2017 was just a deprecation warning in googletest. 

However, I am a little stuck with 2013 - it looks like blobs do not get handled properly. Does anyone have more information? Is this a general problem when compiling sqlite3 with MSVC2013 or is this related to SQLiteCPP?

**Comment by SRombauts** [comment]
I am happy that I had the time and energy to find this little quirks with Unit Tests under MSVC2013; was just that the binding of a char[] through a void* pointer was using the bind(char*) instead of bind(void*)

I just had to use an unsigned char[] for the buffer (as is already the norm for a binary blob in fact), so all is good now.

Thanks again for reporting this :)
Cheers!
