### ISSUE TITLE
How sanitizing is managed by the SQLiteCpp library?

### ISSUE THREAD

**Issue by AndresDuque** [SRombauts/SQLiteCpp#350]
Hi,

I didn't find any examples of sanitizing.

I would like to do something like:

    std::string m_insert = "INSERT INTO table_name (x,y,z) VALUES ( quotes(x), quotes(y), quotes(z))" .

To check if the attributes coming from an object are already quoted or not for preventing SQL Injection. Does the API have such a function?

Thank you in advance @SRombauts .

**Comment by kcowolf** [comment]
Would something like the following cover what you're looking for?

```
SQLite::Statement statement(m_database, "INSERT INTO table_name (x,y,z) VALUES (?, ?, ?)");
statement.bind(1, x);
statement.bind(2, y);
statement.bind(3, z);

statement.exec();  // or statement.executeStep(), etc.

statement.reset();  // Can execute the statement again after this.

statement.clearBindings();  // Can bind new values after this
```

This prevents SQL injection from the x, y, and z variables because the SQL statement is compiled as a SQLite prepared statement when the SQLite::Statement constructor is called.  Binding x, y, and z afterwards ensures they are always treated as values and not as additional SQL code to execute.

https://github.com/SRombauts/SQLiteCpp/blob/master/tests/Statement_test.cpp has examples of statements and binding.

**Comment by AndresDuque** [comment]
Hi @kcowolf ,

Yes, that's exactly what I am looking for, thank you so much!
