### ISSUE TITLE
Best practice to encrypt and decrypt SQLite DB

### ISSUE THREAD

**Issue by AndresDuque** [SRombauts/SQLiteCpp#353]
Hi there,

I would like to encrypt my DB using the SQLiteCpp library. I saw the examples regarding this topic using a key to encrypt or decrypt the DB (`db.rekey("123secret");`)

What's the best practice to define this key avoiding to hardcode the key?

Best regards,
A

**Comment by bentonstark** [comment]
I am looking at this issue as well.  I would like to utilize the sqlite3_serialize and sqlite3_deserialize APIs so I can serialize/encrypt/persist a modest sized database file.  I can then decrypt/deserialize and load the database into an in-memory sqlitedb for use.  The problem I am running into is there is no support through SQLiteCpp for sqlite3_serialize and sqlite3_deserialize.  I will probably look at trying to add them unless there is a method to just call them directly around the SQLiteCpp wrapper.  Any suggestions / techniques to call sqlite3 APIs directly would be greatly appreciated.

**Comment by bentonstark** [comment]
The sqlite3 database never provided native encryption support but rather provided an API for 3rd party plugins (and of course their own).  After some research, it appears the developers of sqlite3 removed support for straight forward 3rd party encryption plugins in 2020.  The developer of wxsqlite3 discovered this rather unexpectedly when attempting to [compile his own code](https://sqlite.org/forum/forumpost/7d7f6633f1).   Below are his comments on the wxsqlite3 github concerning the problem and his solution.

> With the release of SQLite version 3.32.0 on May 22, 2020 critical changes to the public SQLite code finally took officially effect, although they weren't officially announced. They were introduced on Feb 7, 2020: ["Simplify the code by removing the unsupported and undocumented SQLITE_HAS_CODEC compile-time option"](https://www.sqlite.org/src/timeline?c=5a877221ce90e752). As a consequence, updating the wxSQLite3 encryption extension to support SQLite version 3.32.0 and later was no longer possible.
> 
> Since August 2020 a new implementation of an encryption extension, capable of supporting SQLite version 3.32.0 and later, is available as a separate project, [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers). Starting with the release of wxSQLite3 4.6.0 this new implementation is used.

This leaves some rather limited solutions for encrypting sqlite3 databases.
1. Buy a [USD 2,000 license](https://www.sqlite.org/see/doc/release/www/index.wiki) from the sqlite3 developers.
2. Buy a license from [SQLiteCrypt](http://www.sqlite-crypt.com/).  It is unclear if their solution supports sqlite3 3.32.0 and later. 
3. Use the open source  [SQLCipher](https://www.zetetic.net/sqlcipher/).  There is a community edition as well as commercial licensed editions.  Note that SQLCipher is a standalone fork of sqlite.  It is not clear how the developer pulls new sqlite features back into their solution or if there are compatibility issues with SQLiteCpp.
4. Use the open source [wxSqlite3](https://github.com/utelle/wxsqlite3) or newer [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers) implementation.  Note both of these solutions require heavy use of the wxWidgets library dependencies since it was always intended to be a wxWidget.  The newer solution (SQLite3 Multiple Ciphers) must modify the core sqlite3 code and in rather complex since implementation is at the sqlite VFS interface layer.
5. Encrypt your data prior to storing via application level encryption.
6. Use the sqlite3_serialize and sqlite3_deserialize APIs to decrypt a sqlite3 database from disk into memory.  Obviously the size and memory footprint is going to be a limiting factor.

I am going to first implement 6 since my database is rather small.  I have created a PoC and proven that the serialization APIs work as expected and that I can invoke them directly since SQLiteCpp provides a way to easily get the pointer to the sqlite database (getHandle()) and does not support them at this time (although it would be fairly trivial to add).

**Comment by AndresDuque** [comment]
Hi @bentonstark,

Thank you for all the information. At the moment, I am using a library called cryptopp to encrypt the DB and the DB data. You could have a look there as well.

**Comment by AndresDuque** [comment]
FYI, I just encrypted the content of the DB using the CryptoPP library. I am using the Galois/Counter Mode for that, also to check authenticity. It works like a charm and I have no hardcoded key or anything.
