### ISSUE TITLE
[question] How to work with Blob?

### ISSUE THREAD

**Issue by paulocoutinhox** [SRombauts/SQLiteCpp#369]
Hi,

How to work with Blob data?

First, to store, im using `query.bindNoCopy(":value", static_cast<const void*>(value.data()), value.size());`. It is correct?

Second, how to read from `blob` returning a `vector` of `uint_8`? Im trying convert `query.getColumn("value").getBlob()` to `std::vector<uint8_t>`. There is a way to do it?

Thanks.

**Comment by paulocoutinhox** [comment]
My solution is this:

```
int size = query.getColumn("value").getBytes();
char* p = (char*)query.getColumn("value").getBlob();
return std::vector<uint8_t>(p, p+size);
```

Is this made using correct way?

**Comment by SRombautsU** [comment]
Hello,

Your question made me check the examples/example1/main.cpp where I tried to have examples for all the most important features. Unity tests could help with that.
And if you feel they don't show enough, we could actually just add more using more modern c++ since the one I provider are "zero allocation" ie not std::vector<> with allocation but eg "char buffer[1024]" that uses the stack directly

**Comment by SRombautsU** [comment]
And to answer more directly your question, what you are doing is right;

This will make a copy of the content of the pointer p into the vector
> std::vector<uint8_t>(p, p+size);
The memory allocated by SQLite for the content of the pointer p will be released when the query will be destroyed (typically when it goes out of scope, after the return statement

**Comment by SRombauts** [comment]
Hello,

Your question made me check the examples/example1/main.cpp where I tried to have examples for all the most important features. See
 -  https://github.com/SRombauts/SQLiteCpp/blob/ac7541aaf75529d7ed9c0dee51a7f5d1b12b5d4c/examples/example1/main.cpp#L401

Unit tests could also help with that, see
- https://github.com/SRombauts/SQLiteCpp/blob/b611b5cf2859b9d7b982920ac9b7e4dfae83e062/tests/Statement_test.cpp#L412
- https://github.com/SRombauts/SQLiteCpp/blob/ec887cf05ed9fcf2b24a67c9c5ab8089aac9a2a4/tests/Column_test.cpp#L75

And if you feel they don't show enough, we could actually just add more using more modern c++ since the one I provided are "zero allocation" ie not std::vector<> with allocation but eg "char buffer[1024]" that uses the stack directly.

Cheers!

**Comment by SRombauts** [comment]
But, to answer your question, what you are doing is right;

This will make a copy of the content of the pointer p into the vector
> std::vector<uint8_t>(p, p+size);
The memory allocated by SQLite for the content of the pointer p will be released when the query will be destroyed (typically when it goes out of scope, after the return statement

Sébastien
