### ISSUE TITLE
Multi-threads SQLite table operations / synchronization / transactions

### ISSUE THREAD

**Issue by dimy-x** [SRombauts/SQLiteCpp#433]
Hello,

I'd like to know in case of read / write operations on the same SQLite database table from different parallel threads - what should I do in order to synchronize these operations ?

Another questions is about - when to use SQLite transactions ? - Everytime I modify a table through a SQL query ?

Thank you very much in advance,
DimyX

**Comment by dimy-x** [comment]
Come on, guys, I need your support :)

**Comment by dimy-x** [comment]
Please guys, I need some support, does anybody can help me with my questions ? Many thanks in advance

**Comment by SRombauts** [comment]
Hello @dimy-x, I am sorry I was too busy and nobody else felt compelled to answer your questions.

The thing is that you are not asking about this SQLiteC++ wrapper, but about the underlying SQLite database; I bet there are much better places for that (for instance Stack overflow, forums, or Discord servers perhaps).

> I'd like to know in case of read / write operations on the same SQLite database table from different parallel threads - what should I do in order to synchronize these operations?

From my experience, you should absolutely avoid this unless you have a very deep knowledge of the multithreaded architecture; trying to have multiple threads access the database at the same time in serialize mode leads to low-level wait-and-retry that absolutely destroys performances under the hood

> Another questions is about - when to use SQLite transactions ? - Everytime I modify a table through a SQL query ?

It depends. It's either a matter of coherence (if you want to ensure that all succeed or are all reverted) or performances.
For performances with small apps and little queries, it usually doesn't matter, but as soon as you want to execute "scripts" with a series of queries writing data in sequences, you should wrap all the writes in a transaction

**Comment by dimy-x** [comment]
Hello Sebastian,

Thanks a lot for your answer.

I've asked by email another guy working on your SQLite wrapper about the database access from multiple threads at the same time and he told me that it will be fine as far as I create the database object in each thread and I don't share it between the threads:

SQLite::Database    db("database.db3", SQLite::OPEN_READWRITE|SQLite::OPEN_CREATE);

Could you please confirm me this ?

Please, could you please answer my question ASAP , because I will start implementing with the library.

Many thanks,
dimy-x

**Comment by dimy-x** [comment]
Hello Sebastien,

In addition to my previous question - should I also use some kind of mutex synchronization of the database object or it is already sufficient only to have in each thread its personal database connection object:

SQLite::Database db("database.db3", SQLite::OPEN_READWRITE|SQLite::OPEN_CREATE)

And doing so, Could I have without problems concurrent writes from multiple threads on the same database table ?

Many thanks in advance,
dimy-x

**Comment by dimy-x** [comment]
Hello Sebastien,

I've added two questions to my request on GitHub.

Could you please answer them ASAP, because I'm kind of stuck..

Many thanks in advance,
dimy-x

**Comment by dimy-x** [comment]
Hello Sebastien,

Please, give me your advise, as soon as you have time.

Many thanks in advance,
dimy-x

**Comment by dimy-x** [comment]
Come on, guys, plase could you answer my last questions ?

**Comment by EvanBalster** [comment]
As far as I can tell, current best practices are to put the database in write-ahead logging mode with the [SQLITE_OPEN_WAL](https://sqlite.org/wal.html) flag, which the developers recommend for most multi-threaded and multi-process use cases.  This makes it so that writers don't block readers and vice versa.

That leaves the problem of concurrent writers.  The path of least resistance is to use an application mutex to prevent multiple writes from occurring simultaneously.  Alternatively, if you're willing to do more work, true concurrent writes are possible with [BEGIN CONCURRENT](https://sqlite.org/src/doc/begin-concurrent/doc/begin_concurrent.md) but these may fail if two writers try to change "nearby" entries on the same table.  When this happens, one of the writers will get a `SQLITE_BUSY_SNAPSHOT` code.

SQLiteCpp does not currently include flags for WAL mode or concurrent transactions but you can access this functionality by including `sqlite3.h` directly.
