### ISSUE TITLE
Can this lib build for iOS?

### ISSUE THREAD

**Issue by Vienta** [SRombauts/SQLiteCpp#76]
RT

**Comment by SRombauts** [comment]
It should, yes, but the CMakeLists.txt would need some modifications, I suppose!

I cannot test this without a Mac. Can you try this and report here for everyone else?

**Comment by HighSparrow** [comment]
what do you need, @Vienta ?

**Comment by Vienta** [comment]
@HighSparrow   I have a project want to use c++ sqlite lib for cross-platform.Then I find this lib.Do you have any advices?

**Comment by HighSparrow** [comment]
@Vienta  It is MIT licensed, just use the codes directly as an external part if your project is in c++. 
There is no cocoapods for it, I think. 
To build it as a static lib, you can port these codes in a Xcode project and use *xcodebuild* to generate libs for simulators and devices and then you can archive those libs in different archs as one by *lipo*.

**Comment by Vienta** [comment]
@HighSparrow  
Thx for you advice.I'll try it.

**Comment by SRombauts** [comment]
Hi, thanks for the advices, and please come back with your results when you get some.

**Comment by 4brunu** [comment]
Hey, I'm having the same problem.
@Vienta Do you solve this problem?
I'm trying to import the source files instead of creating a static lib, but the imports give me an error.
I think it’s because the import’s inside the library are #include <SQLiteCpp/Database.h> and not #include “Database.h”, but I’m not sure, could anyone help please?
I create a github repo as an example. Thanks
https://github.com/4brunu/SQLiteCppExample

**Comment by zhouxiaoxiaoxujian** [comment]
@4brunu  You should set 'Header Search Paths' like 'your_path_to/deps/SQLiteCpp/include' in xcode 'Building settings'.

**Comment by 4brunu** [comment]
@zhouxiaoxiaoxujian thanks a lot, it worked! You made my day ;)
