### ISSUE TITLE
UTF16 support

### ISSUE THREAD

**Issue by xTachyon** [SRombauts/SQLiteCpp#78]
Hello. I was kind of shocked when I saw your wrapper does not support for UTF16 strings. I don't know why, but I through it supports all the features of sqlite.

From sqlite site: Support for both UTF-8 and UTF-16 text.

I understand sizeof(wchar_t) on Linux is 4 bytes will not be portability if you use it.. but really, I think there are another solutions(ex: if sizeof(wchar_t) != 2 -> shrink to fit or kind of own string class implementation with underlying int16_t or.. I don't know).

My problem is about working with files and no ASCII / UTF8 filenames, but UTF16. What should I do ? Do you mind if you add such a support or do I need to use the sqlite library directly ?

Thanks, Andrei.

**Comment by SRombauts** [comment]
Hi, yes this is related to question  #33 No `wstring` overloads: I do not plan to add full UTF16 support as this is not portable or will require much work on my part (that I don't have).

You could try to add this support where you need it, and provide me with a pull request so that I could integrate it into the master branch!

Cheers!

**Comment by xTachyon** [comment]
Hello ! Thanks for your response.

I will see if I can do anything. I am still not sure if I'll go for adding the support or not.
